### PR TITLE
jsxstyle

### PR DESCRIPTION
**Pull request by lettertwo**
# Description of Changes

This PR adds a [jsxstyle](https://github.com/smyte/jsxstyle) example.
Though jsxstyle is *much* more React-centric than many of the other alternatives showcased on this playground, I believe that React is implied by all of them. If you feel differently, feel free to disregard!

# Checklist

Please make sure each of the following is validated:

- [x] `yarn test` passes
  - If anything fails, try to fix the test, or perhaps update the snapshot `yarn test -u`
- [x] `yarn test:integration` passes
  - If a snapshot, update the visual regression snapshot(s) with `yarn test -u`
- [x] `yarn lint` passes
  - If any linting issues, try and fix them, or run `yarn lint --fix` to try and automatically fix them
- [x] Netlify deploy looks good
  - Netlify will run on every PR and update with a comment when the site is ready; check it out, and do a quick sanity check!

Thank you for your contribution(s)!

### CODE REVIEW

**Comment by DSchau** [comment]
@lettertwo awesome! Let's take a look at the netlify deploy preview, but this is looking good!

**Comment by DSchau** [comment]
Deploy preview ready!

Built with commit 8f95b1a66213bd69228668d02052ec623b222c44

https://deploy-preview-103--css-in-js-playground.netlify.com

**Comment by DSchau** [comment]
Looking like the integration tests are a bit flaky, but think we're good to go on this. Merging!

**Comment by lettertwo** [comment]
Wow, this has to be a PR-to-merge record! 🎉  Thanks for merging, and for this great app!

**Comment by DSchau** [comment]
Of course! Thanks for the PR 👍

**Comment by DSchau** [comment]
Fixed the flaky tests and jsxstyle is now up :)

https://www.css-in-js-playground.com/?activeModule=index&library=jsxstyle

(note you may have to "reload" the service worker, it should prompt you to do so in Chrome, Firefox, etc.)

**Pull request merged**
