### PR TITLE
add fela example

### PR DESCRIPTION
**Pull request by robinweser**
# Description of Changes

I added an example using Fela.

# Checklist

Please make sure each of the following is validated:

- [x] `yarn test` passes
  - If anything fails, try to fix the test, or perhaps update the snapshot `yarn test -u`
- [x] `yarn test:integration` passes
  - If a snapshot, update the visual regression snapshot(s) with `yarn test -u`
- [x] `yarn lint` passes
  - If any linting issues, try and fix them, or run `yarn lint --fix` to try and automatically fix them
- [x] Netlify deploy looks good
  - Netlify will run on every PR and update with a comment when the site is ready; check it out, and do a quick sanity check!

Thank you for your contribution(s)!

### CODE REVIEW

**Comment by DSchau** [comment]
Deploy preview ready!

Built with commit a2d7c07de3ea53111c2002c6e85851ac431b6c35

https://deploy-preview-100--css-in-js-playground.netlify.com

**Comment by DSchau** [comment]
Awesome, this is so great!!

Thank you, I’ll merge this in a bit

**Comment by robinweser** [comment]
Done. Forgot to remove that, used to test if the preset was imported correctly as I had a hard time to understand what is actually going on in that `libraries.js` file 😅

Thank you!

**Comment by DSchau** [comment]
Whoa! So what happened in that latest commit? Looks like a bunch of stylistic changes!

**Comment by robinweser** [comment]
Alright sorry, was my local Prettier config I guess.
Fixed it.

**Review by DSchau — COMMENTED** [review]
Ugh, well for some reason build is failing and I’m away from computer until tomorrrow afternoon.

I’ll merge then if that’s cool, want to make sure Travis failure isn’t anything substantive!

Thanks again for the PR!

**Comment by robinweser** [comment]
No worries! Ping me if there's something I forgot or whatever, although all tests + build is working fine for me locally.

**Comment by DSchau** [comment]
Of course, thanks for being understanding!

Excited to have fela up and included!

**Comment by DSchau** [comment]
Yikes, screwed something up. Looking into it!

**Comment by DSchau** [comment]
@rofrischmann merged! Should see fela in the playground in about 5 minutes :)

Thanks again!

**Comment by robinweser** [comment]
Amazing, thank you!

**Pull request closed without merging**
