### PR TITLE
Refactor react-jss

### PR DESCRIPTION
**Pull request by kof**
A better separation of components. Ideally I would put each of those in separate files, but not sure if you want this change. 

I think this component in general is too big for this file.

### CODE REVIEW

**Comment by DSchau** [comment]
No, I love this! Like I said, I am not a JSS power user by any means, so this seems a lot nicer to me.

I'll check out this branch locally and validate, but this is looking great!

**Comment by DSchau** [comment]
Also @kof I agree! The idea wasn't to show a perfect representation of a React "view" but rather just show some common authoring practices and display each CSS in JS solution side by side!

**Comment by kof** [comment]
Sometimes small things, which can be easily fixed, result in a negative perception of readability.
For e.g.
- a big render function
- big component
- unrelated logic in one component

What I would do here:
- validation with state - separate component
- all rendering - separate
- stripes should part of the the header
- one component per file

**Comment by kof** [comment]
For e.g. if you want to compare with styled-components in terms of readability, you need to do those things, because that huge render block and huge component looked really bad compared to SC, but this doesn't have to be that way.

**Comment by DSchau** [comment]
I agree, but remember and note that that was not my intention! I brought you in for just this purpose, so I'm glad we're making it a fairer comparison!

**Comment by kof** [comment]
I just hope this repo will gain popularity and when it does, it should help makin decisions, thats why it  is important to show best possible ways of using them, not just the most primitive onces.

**Comment by DSchau** [comment]
@kof agreed! One other thing that some may find helpful is a comment or comments when something may be non-ideal for the sake of demonstration. For example, as you note, each of those pieces would typically be in a separate file, so that could be commented/documented to make it clear

**Comment by kof** [comment]
We can do comments, though this is suboptimal, in separate files there are separate scopes and though some variable naming would be different. Also don't forget that people don't read everything. They skim most of the time.

**Comment by DSchau** [comment]
@kof agreed, but at a certain point, we also need to remember the scope of the original project too. I can probably build in some form of rudimentary file system but I think that adds a great deal of complexity when this is intended to show the general idea at a quick glance.

So there are certainly some trade offs made along the way, but I think we're getting closer with this.

Also checked it out, it looks great. Thanks!

**Comment by kof** [comment]
> rudimentary file system

Sounds easy to me, imports should just work, right? Seems it is about to just put each snippet into separate folder and let each implementation decide the files structure.

**Comment by DSchau** [comment]
Right, but how are you going to show the implementation/content of those files? I'd need to build in a sidebar and then at that point I'm just building CodeSandbox.

**Comment by kof** [comment]
Damn, forgot about that. Maybe it would be actually a good idea to embed codesandbox, because it has a possibility to load from a repo.

**Comment by kof** [comment]
A minimalistic interface would be to just have a select box on top next to implementation select which would list the file names, initially you would see the index.js

**Comment by DSchau** [comment]
That's a good idea. So you'd start on index.js, but would be able to view each of the files. I still like the idea of all of them in one place, even though (as we both admit) it's not the best for code clarity or for real world best practices.

I think the central idea is getting people to, at a glance, get some exposure to the particular library. I think this accomplishes that!

**Comment by DSchau** [comment]
Also this same approach that you've done here should be done for JSS proper as well, correct? I can do that now

**Comment by kof** [comment]
I know there is a strong sentiment regarding putting styles into js files, because people don't know how to write readable components in that way. I was asked 1000 times how to make components with styles inside still readable.

I think you overestimate peoples ability to imagine how it could be properly done. Don't rely on that, 90% will do that wrong.

**Comment by DSchau** [comment]
We're actually agreeing; I just disagree with going the extra 25% (let's say we're at 75% best practice). I think the complexity involved in going to that level mitigates the benefit of what was supposed to be a simple "at a glance" tool to give people high level exposure to a great variety of these libraries

But that said, you should know by now I'm all about PRs from others, and I'd happily entertain alternate mechanisms of displaying stuff, especially if you can implement some of your ideas!

**Comment by kof** [comment]
So do you think having a select box with files on top is acceptable? Showing just index.js by default, which should contain the main render component.

**Comment by DSchau** [comment]
I think it could work. I'd be interested to see whether that detracts/confuses from seeing the actual code for the library!

I also think there's some level of complexity (not a ton, but some) in managing each of those disparate files and then "merging" them when transpiling to the code preview.

What do you think? Think it's doable and worth it?

**Comment by DSchau** [comment]
I think there's also probably a cleaner/more intuitive UI for doing something like that, but I (obviously) have not found that yet!

**Pull request merged**
