### PR TITLE
add linaria support

### PR DESCRIPTION
**Pull request by Tushkiz**

### CODE REVIEW

**Comment by DSchau** [comment]
Deploy preview ready!

Built with commit 5b540c4e4a5b951e9f4bfd6f7d3304d9df4a2540

https://deploy-preview-74--css-in-js-playground.netlify.com

**Comment by DSchau** [comment]
@Tushkiz it looks great :) I'll merge this in!

Also [sneak peak](https://deploy-preview-70--css-in-js-playground.netlify.com) of something that's coming soon! Let me know what you think!

I'll add Linaria and break it up into separate files in that branch!

**Comment by Tushkiz** [comment]
Wow, that is lit 🔥 

I have a suggestion, can we place the new tab "➕" icon right after the last tab (just like browsers)? It took me a considerable amount of time to figure out that we can add a new file to the playground.

**Comment by DSchau** [comment]
That is a great idea! I tend to do “mobile first” (and I like it aligned right on mobile) but that’s a great enhancement idea for progressively larger screens!

I’ll build that in, thanks! Did the cancel button (that appears when adding a file) make sense?

**Comment by Tushkiz** [comment]
woah, totally missed that one. I used `escape` key to cancel.
I think on a larger screen it should be tied to the input box (mostly towards the right) and on a mobile screen, it should replace ➕ button.

**Comment by DSchau** [comment]
Love those ideas! Thank you!!

**Comment by Tushkiz** [comment]
You are most welcome 👍

**Comment by DSchau** [comment]
@Tushkiz I think I accommodated each of your suggestions!

[Check it out](https://deploy-preview-85--css-in-js-playground.netlify.com/) and let me know if you get a chance!

**Comment by Tushkiz** [comment]
Niice! that was quick, it is looking much more advanced playground 🤘
Can we target the dropdown next, maybe a custom one with logos

**Comment by DSchau** [comment]
@Tushkiz heh, we are on the same page! #79 

I was thinking a link/button in the bottom left of the playground, but a custom select could be cool too

**Comment by Tushkiz** [comment]
Cool! custom dropdown definitely would blend well (logos besides library) and you won't need separate links (save space)

**Comment by DSchau** [comment]
Unfortunately, they don't _each_ have logos as far as I know! Aphrodite doesn't :/ But I agree!

I wish they all used emoji like a few of them do, then it'd be very simple

**Comment by Tushkiz** [comment]
Ohh, that's bad 😲

**Pull request merged**
